name: acplt-emu

on: 
  push:
    paths:
      - .github/workflows/acplt-emu.yml
      - acplt/emulation/**
      - '!acplt/emulation/**/README.md'

jobs:
  build:
    name: Build Emulation
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: acplt/emulation/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          projectPath: acplt/emulation

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: acplt/emulation/build